In [3]:
# Yttri lab dataset processing

import numpy as np
import random
import scipy as sp
from scipy import io

In [9]:
# Get training and testing data
d1 = np.loadtxt('./depth1', delimiter= ',')
d2 = np.loadtxt('./depth2', delimiter= ',')
m1 = np.loadtxt('./Mborder1', delimiter= ',')
m2 = np.loadtxt('./Mborder2', delimiter= ',')

In [19]:
d1.shape
# max(d1)
# min(d1)

(255,)

In [18]:
d2.shape
# max(d2)
# min(d2)

(385,)

In [11]:
m1.shape


(2,)

In [12]:
m2.shape

(2,)

In [ ]:
# time is 38 minutes for the last timesets

In [25]:
# classify the neurons based on their depth

# 2 is ventral striatum
# 1 is dorsal striatum
# 0 is motor cortex

type1 = np.empty_like(d1)
for i in range(len(d1)):
    if 0.0 <= d1[i] < m1[0]:
        type1[i] = 0
    elif m1[0] <= d1[i] < 3.0:
        type1[i] =1
    else:
        type1[i] = 2

In [26]:
type1

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1

In [27]:
type2 = np.empty_like(d2)
for i in range(len(d2)):
    if 0.0 <= d2[i] < m2[0]:
        type2[i] = 0
    elif m2[0] <= d2[i] < 3.0:
        type2[i] = 1
    else:
        type2[i] = 2

In [28]:
type2

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  1.,  1.,  2.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1

In [32]:
np.savetxt('type1.txt', type1, delimiter=',', fmt='%i')
np.savetxt('type2.txt', type2, delimiter=',', fmt='%i')

In [93]:
#tss is a neuron x timestamp array. Each row is a different neuron.  
tss1 = np.loadtxt('./tss1', delimiter= ',')*10
tss2 = np.loadtxt('./tss2', delimiter= ',')

KeyboardInterrupt: 

In [95]:
tss1.shape
tss1 = tss1*10.0 # there's a mistake in TSS1!

In [49]:
tss2.shape
len(tss2) 

385

In [96]:
tss1[1]

array([   16.033,   837.73 ,  2668.1  , ...,       nan,       nan,
             nan])

In [98]:
print np.nanmin(tss1)
print np.nanmax(tss1)#/60000
print np.nanmin(tss2)
print np.nanmax(tss2)#/60000

5.9333
38.7533333333
5.0333
33.45


In [116]:
# make a matrix to store the time intervals which I should use. 
mat1 = np.zeros((len(tss1), int(np.floor(np.nanmax(tss1)))+1), dtype=int)
mat2 = np.zeros((len(tss2), int(np.floor(np.nanmax(tss2)))+1), dtype=int)

In [79]:
mat1.shape

(255, 232521)

In [80]:
mat2.shape

(385, 2007001)

In [81]:
# for each time in each neuron, ignoring NANs, 
# fill in the entry in the corresponding timepoint
# rows are neurons,
print len(tss1)
print len(mat1)

255
255


In [110]:
mat1.shape

(255, 2325201)

In [112]:
len(tss1[0])/500.0

318.172

In [106]:
tss2.shape

(385, 90631)

In [113]:
len(tss2[0])/500.0

181.262

In [122]:
# make mat1
for i in range(len(tss1)):
    # for each neuron
    for j in range(len(tss1[1])):
        # for each time 
        if not np.isnan(tss1[i][j]):
            time = int(np.floor(tss1[i][j]))
            mat1[i][time] = 1

IndexError: index 4809 is out of bounds for axis 0 with size 4651

In [118]:
# make mat2
for i in range(len(tss2)):
    # for each neuron
    for j in range(len(tss2[1])):
        # for each time 
        if not np.isnan(tss2[i][j]):
            time = int(np.floor(tss2[i][j]))
            mat2[i][time] = 1

In [121]:
# check there is firing and everything is ok
mat1[4][50:60]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1,

In [120]:
# check there is firing.
max(mat2[1])

1

In [105]:
# now save
np.savetxt('mat1.txt', mat1, delimiter=',', fmt='%i')
np.savetxt('mat2.txt', mat2, delimiter=',', fmt='%i')

In [124]:
mat1 = np.loadtxt('mat1.txt',delimiter=',')
mat2 = np.loadtxt('mat2.txt',delimiter=',')

KeyboardInterrupt: 

In [ ]:
mat1_sep = np.zeros((len(tss1), int(np.floor(np.nanmax(tss1/500.0)))+1), dtype=int)


In [ ]:
mat2_sep = np.zeros((len(tss2), int(np.floor(np.nanmax(tss2/500.0)))+1), dtype=int)

In [ ]:
# now separate into intervals of 500ms
# make mat1
for i in range(len(tss1)):
    # for each neuron
    for j in range(len(tss1[1])):
        # for each time 
        if not np.isnan(tss1[i][j]):
            time = int(np.floor(tss1[i][j]))
            mat1[i][time] = 1

In [ ]:
# make mat2
for i in range(len(tss2)):
    # for each neuron
    for j in range(len(tss2[1])):
        # for each time 
        if not np.isnan(tss2[i][j]):
            time = int(np.floor(tss2[i][j]))
            mat2[i][time] = 1